In [3]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('Advertising.csv').values

data=dataset[:,1:4]
target=dataset[:,4]

target=np.reshape(target,(-1,1))

print(data[:10])
print(target[:10])
print("Size of dataset:",len(dataset))

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]]
[[22.1]
 [10.4]
 [ 9.3]
 [18.5]
 [12.9]
 [ 7.2]
 [11.8]
 [13.2]
 [ 4.8]
 [10.6]]
Size of dataset: 200


In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.2)

In [6]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(X_train,y_train)

predicted_target=model.predict(X_test)

In [9]:
from sklearn.metrics import r2_score

r2=r2_score(y_test,predicted_target)
print("r2 score:",r2)

r2 score: 0.9060209219426256


In [11]:
import joblib
joblib.dump(model,'Advertising_sales_revenue.sav')

['Advertising_sales_revenue.sav']